apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort  # Opciones: ClusterIP, NodePort, LoadBalancer según tus necesidades
